# Nixpacks configuration for Turborepo - apps/web only
[variables]
NODE_ENV = "production"
PORT = "3000"
HOSTNAME = "0.0.0.0"

# Use Bun as package manager and Node.js for runtime
[phases.setup]
nixPkgs = ["bun", "nodejs"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = [
  "bun run build --filter=web",
  "cp -r apps/web/.next/static apps/web/.next/standalone/apps/web/.next/static",
  "cp -r apps/web/public apps/web/.next/standalone/apps/web/public"
]

[start]
cmd = "cd apps/web/.next/standalone && node apps/web/server.js"