name: Build and Deploy to Dokploy

on:
  push:
    branches: ["main"]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install nixpacks
        run: |
          curl -sSL https://nixpacks.com/install.sh | bash
          echo "$HOME/.nixpacks/bin" >> $GITHUB_PATH

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/portfolio
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build Docker image with nixpacks
        run: |
          nixpacks build . --name ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
          docker tag ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/portfolio:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/portfolio:latest

      - name: Trigger Dokploy deployment
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST "${{ secrets.DOKPLOY_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{"ref": "refs/heads/main", "repository": {"full_name": "${{ github.repository }}"}}'
        env:
          DOKPLOY_WEBHOOK_URL: ${{ secrets.DOKPLOY_WEBHOOK_URL }}

      - name: Deployment status
        if: github.ref == 'refs/heads/main'
        run: |
          echo "🚀 Deployment triggered successfully!"
          echo "📦 Docker image: ghcr.io/${{ github.repository_owner }}/portfolio:latest"
          echo "🔗 Webhook URL called: ${{ secrets.DOKPLOY_WEBHOOK_URL }}"